const DB_HOST = 'DB_HOST';
const DB_PORT = 'DB_PORT';
const DB_USERNAME = 'DB_USERNAME';
const DB_PASSWORD = 'DB_PASSWORD';
const DB_NAME = 'DB_NAME';

export { DB_HOST, DB_NAME, DB_PASSWORD, DB_PORT, DB_USERNAME };
